version: '3.8'

services:
  sql-db:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sql1
    hostname: sql1
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Admin!2025 
    volumes:
      - sqlserver-data:/var/opt/mssql/data
     
volumes:
  sqlserver-data: